--1. 학생이름과 주소지를 표시하시오. 단, 출력 헤더는 "학생 이름", 주소지로
--정렬은 이름으로 오름차순
SELECT STUDENT_NAME,STUDENT_ADDRESS
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2.휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN ='Y'
ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;

--3. 주소지가 가원도나 경기도인 학생들 중 1900년대 학번을 가진학생들의
--이름과 학번 주소를 이름의 오름차순으로 출력
SELECT STUDENT_NAME AS "학생이름",
        STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거구지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE ('강원도%') OR 
      STUDENT_ADDRESS LIKE ('경기도%') AND
      STUDENT_NO LIKE ('9%')
ORDER BY STUDENT_NAME;

--4. 현재 법학과 교수중 가장 나이가 많은 사라부터 이ㅏ름을 확인할 수 있는
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY SUBSTR(PROFESSOR_SSN,1,6);

--5.2004 년 2GKRRLDP C3118100 과목을 수강한 학생들의 학점조회
--학점이 높은 학생부터 표시 학점이 같으면 학번이 낮은 학생부터 표시
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND
        TERM_NO = 200402
ORDER BY POINT DESC, STUDENT_NO;

--6.학생번호 이름 하과 이름을 학생이름으로 오름차순
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7. 춘 기술대학교의 과목 이름과 과목의 학과 이름을 출력
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8.과목별 교수이름을 찾아야한다. 과목이름 교수
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9. 8번의 결좌중 인문사회 계열에 속한 과목의 교수 찾기
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE CATEGORY = '인문사회';

--10. 음악학과 학생들의 평점을 구하려고 한다. 음악학가 학생들의 학버
-- 이름 전체 평점 을 출력하라 단, 평점은 소수점 1자리
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT),1) AS"전체 평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;

--11. 학번이 A313047인 학생이 학교에 나오고 있지않다 내용전달을 위해 학과이름 학생이름 지도교수이름
SELECT DEPARTMENT_NAME AS "학과이름", STUDENT_NAME AS"학생이름", PROFESSOR_NAME AS "지도교수이름"
FROM tb_department
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN tb_professor ON (coach_professor_no = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12.2007년도에 인간관계롤 과목을 수강한 학생을 찾아 학생이름과 수강학기름 표시해라
SELECT STUDENT_NAME, TERM_NO AS TERM_NAME
FROM tb_student
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) ='2007' AND CLASS_NAME = '인간관계론';

--13.예체능 계열 과목 중 과목 담당교수를 한명도 배정받지 못한 과목을 찾아라
-- 과목이름 학과 이름
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
LEFT JOIN tb_class_professor D ON(C.CLASS_NO = D.CLASS_NO)
JOIN TB_DEPARTMENT B ON (C.DEPARTMENT_NO = B.DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND D.CLASS_NO IS NULL;

--14. 춘기술 대학교 서반아어학과 학생들의 지도교슈를 게시하고자 한다 학생이름과
--지도교수 이름을 찾고 만일 지도교수가 없는 학생일 경우 '지도교수 미지정'
SELECT STUDENT_NAME AS "학생 이름", NVL2(PROFESSOR_NO, PROFESSOR_NAME, '지도교수 미지정') AS "지도 교수"
FROM tb_student Q
JOIN tb_department D ON (Q.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN tb_professor ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';

--15.휴학생이 아닌 학생 중 평점이 4.0이상인 학생을 찾아 그 학생의
--학번 이름 학과 이름 평점을 출력
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, ROUND(AVG(POINT),2)
FROM TB_STUDENT A
LEFT JOIN TB_DEPARTMENT C ON (A.DEPARTMENT_NO = C.DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY STUDENT_NO;

--16.환경조경학과 전공과목들의 과목 별 평점을 파악할수있는
SELECT CLASS_NO, CLASS_NAME, ROUND(AVG(POINT),8)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN tb_department USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME;

--17.최경희 학생과 같은 과 학생들의 이름과 주소
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO= (SELECT DEPARTMENT_NO
        FROM TB_STUDENT
        WHERE STUDENT_NAME = '최경희');
        
--18. 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하라
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME
        FROM TB_STUDENT
        JOIN tb_department USING (DEPARTMENT_NO)
        JOIN tb_grade USING(STUDENT_NO)
        WHERE DEPARTMENT_NAME = '국어국문학과'
        GROUP BY STUDENT_NO,STUDENT_NAME
        ORDER BY AVG(POINT) DESC)
WHERE ROWNUM =1;

--19 환경조경학과가 속한 같은 계열 학과들의 학과 별 전공과목 평점을 파악하기위한 적절한 SQL문을 찾아라
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT),1) AS "전공평점"
FROM tb_department
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE category = (SELECT category
                    FROM TB_DEPARTMENT
                    WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME;


































