-- 헤헤
/* 주석

*/

-- 일반 사용자 계정을 생성하는 구문(오직 관리자 계정에서만 사용할 수 있음)
-- [표현법]  CREATE USER c##계정명 IDENTIFIED BY 비밀번호;
CREATE USER c##SERVER IDENTIFIED BY SERVER;

CREATE USER C##INDEXTEST IDENTIFIED BY INDEXTEST;
--SQL은 대소문자를 구분하지않은 다만 비밀번호는 대소문자를 구분한다


-- 위에서 생성된 일반 사용자계정에 최소한의 권한(접속, 데이터 관리) 부여
--[표현법] GRANT 권한1, 권한2 .... TO 계정;
--ALTER USER [유저명] DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO c##SERVER;
GRANT CONNECT, RESOURCE TO C##TEST;

GRANT CONNECT, RESOURCE TO C##INDEXTEST;
ALTER USER C##TEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER C##INDEXTEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER c##JSP IDENTIFIED BY JSP;
GRANT CONNECT, RESOURCE TO C##JSP;
ALTER USER C##JSP DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER c##MYBATIS IDENTIFIED BY MYBATIS;
GRANT CONNECT, RESOURCE TO C##MYBATIS;
ALTER USER C##MYBATIS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


CREATE USER c##spring IDENTIFIED BY spring;
GRANT CONNECT, RESOURCE TO C##spring;
ALTER USER C##spring DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

